- debug:
    msg: "{{docker_appname}} will be installed"

- name: Create docker directory
  file:
    path: "{{docker_apps_dir}}/{{docker_appname}}"
    state: directory
    owner: docker
    group: docker
    recurse: true
    
- name: copy docker-compose.yml
  template:
    src: apps-{{docker_appname}}-compose.yml
    dest: "{{docker_apps_dir}}/{{docker_appname}}/docker-compose.yml"
 
- name: Run docker-compose
  shell:
    docker-compose up -d
  args:
    chdir: "{{docker_apps_dir}}/{{docker_appname}}"
    
- name: Create a symbolic link
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
  with_items:
    - {src: "{{docker_apps_dir}}/{{docker_appname}}/docker-compose.yml",dest: "/data/config/apps-{{docker_appname}}-compose.yml"}
    - {src: "{{docker_apps_dir}}/{{docker_appname}}",dest: "/data/wwwroot/{{docker_appname}}"}
