---
- name: Create /data/portainer directory
  file:
    path: /data/portainer
    state: directory
    owner: root
    group: root
    mode: 0755

- name: copy docker-compose.yml to /data/config/docker/
  template:
    src: apps_portainer_compose.yml
    dest: /data/portainer/docker-compose.yml
 
- name: Run docker phppgadmin
  shell:
    docker-compose up -d
  args:
    chdir: /data/portainer/
