- name: Create docker app directory
  file:
    path: /data/apps/phpmyadmin
    state: directory
    owner: docker
    group: docker
    recurse: true
         
- name: copy docker-compose.yml to app directory
  template:
    src: apps_phpmyadmin_compose.yml
    dest: /data/apps/phpmyadmin/docker-compose.yml
 
- name: docker-compose up
  shell:
    docker-compose up -d
  args:
    chdir: /data/apps/phpmyadmin
    
- name: Create a symbolic link
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
  with_items:
    - {src: /data/apps/phpmyadmin/docker-compose.yml,dest: /data/config/apps_phpmyadmin_compose.yml}
    - {src: /data/apps/phpmyadmin,dest: /data/wwwroot/phpmyadmin}
