---
- name: Create dir
  file:
    path: /data/wwwroot/onlyoffice_DocumentServer
    state: directory

- name: Copy onlyofficedocumentserver Docker-Compose file
  template:
    src: "apps_onlyofficedocumentserver-compose.yml"
    dest: /data/wwwroot/onlyoffice_DocumentServer/docker-compose.yml

- name: docker-compose up
  shell: docker-compose up -d 
  args:
    chdir: /data/wwwroot/onlyoffice_DocumentServer