---
- name: Create /data/apps/onlyoffice-documentserver directory
  file:
    path: /data/apps/onlyoffice-documentserver
    state: directory
    owner: docker
    group: docker
    recurse: true
    
- name: pull onlyoffice/documentserver image
  shell: sudo docker pull onlyoffice/documentserver
  register: docker_pull_status

- debug: msg="{{docker_pull_status.stdout}}"

- name: Copy docker-compose.yml to /data/apps/onlyoffice-documentserver
  template:
    src: apps_onlyofficedocumentserver-compose.yml
    dest: /data/apps/onlyoffice-documentserver/docker-compose.yml
    
- name: Run onlyoffice/documentserver
  shell:
    docker-compose up -d
  args:
    chdir: /data/apps/onlyoffice-documentserver
    
- block:
  - name: Create cert directory
    file:
      path: /data/apps/onlyoffice-documentserver/data/certs
      state: directory
      recurse: true

  - name: Copy certificate to certs directory
    copy:
      src: "onlyofficedocumentserver/certs/{{item}}"
      dest: /data/apps/onlyoffice-documentserver/data/certs
      mode: 0400
    with_items:
      - onlyoffice.crt
      - onlyoffice.csr
      - onlyoffice.key
      - dhparam.pem

- name: Create symbolic links
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
  with_items:
    - {src: /data/apps/onlyoffice-documentserver/docker-compose.yml,dest: /data/config/docker-compose.yml}
    - {src: /data/apps/onlyoffice-documentserver,dest: /data/wwwroot}
