---
- name: Create dir
  file:
    path: /data/wwwroot/onlyoffice
    state: directory

- name: copy docker-compose.yml
  shell: wget https://raw.githubusercontent.com/ONLYOFFICE/Docker-DocumentServer/master/docker-compose.yml 
  args:
    chdir: /data/wwwroot/onlyoffice

- name: change port
  lineinfile:
    path: /data/wwwroot/onlyoffice/docker-compose.yml
    regexp: "      - '80:80'"
    line: "      - '9002:80'"

- name: run docker-compose
  shell: docker-compose up -d 
  args:
    chdir: /data/wwwroot/onlyoffice