---
- name: pull onlyoffice/documentserver image
  shell: sudo docker pull onlyoffice/documentserver
  register: pull_docker_status

- debug: msg="{{pull_docker_status.stdout}}"

- block:
  - name: Create certs directory
    file:
      path: /data/wwwroot/onlyoffice/DocumentServer/data/certs
      state: directory
      recurse: true

  - name: Copy certificate to certs directory
    copy:
      src: "onlyofficedocumentserver/certs/{{item}}"
      dest: /data/wwwroot/onlyoffice/DocumentServer/data/certs
      mode: 0400
    with_items:
      - onlyoffice.crt
      - onlyoffice.csr
      - onlyoffice.key
      - dhparam.pem

- name: Copy docker-compose.yml to /data/wwwroot/
  template:
    src: apps_onlyofficedocumentserver-compose.yml
    dest: /data/apps/onlyoffice/docker-compose.yml

- name: Run onlyoffice/documentserver
  shell:
    docker-compose up -d
  args:
    chdir: /data/apps/onlyoffice
