- name: Create docker app directory
  file:
    path: /data/apps/phpmyadmin
    state: directory
    owner: docker
    group: docker
    recurse: true

- name: Get Docker Gateway
  shell: ip route show | grep docker0 | awk '{print $9}'
  register: docker_gateway

- name: Run phpMyAdmin container
  shell: sudo docker run --name phpmyadmin  \
         --restart=always \
         -i -t -d \
         -p 0.0.0.0:9090:80 \
         -e PMA_HOST={{docker_gateway.stdout}} \
         phpmyadmin/phpmyadmin
         
- name: copy docker-compose.yml to app directory
  template:
    src: apps_phpmyadmin_compose.yml
    dest: /data/apps/phpmyadmin/docker-compose.yml
 
- name: docker-compose up
  shell:
    docker-compose up -d
  args:
    chdir: /data/apps/phpmyadmin
