- name: Create docker app directory
  file:
    path: /data/apps/phpmyadmin
    state: directory
    owner: docker
    group: docker
    recurse: true

- name: Get Docker Gateway
  shell: ip route show | grep docker0 | awk '{print $9}'
  register: docker_gateway
         
- name: copy docker-compose.yml to app directory
  template:
    src: apps_phpmyadmin_compose.yml
    dest: /data/apps/phpmyadmin/docker-compose.yml
 
- name: docker-compose up
  shell:
    docker-compose up -d
  args:
    chdir: /data/apps/phpmyadmin
