---
- name: Create /data/portainer directory
  file:
    path: /data/portainer
    state: directory
    owner: docker
    group: docker
    mode: 0750

- name: copy docker-compose.yml to /data/config/docker/
  template:
    src: apps_portainer_compose.yml
    dest: /data/portainer/docker-compose.yml
 
- name: Run docker phppgadmin
  shell:
    docker-compose up -d
  args:
    chdir: /data/portainer/
    
- name: Create a portainer symbolic link
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
  with_items:
    - {src: /data/portainer/docker-compose.yml,dest: /data/config/apps_portainer_compose.yml}
