---
- name: Create /data/apps/onlyoffice-documentserver directory
  file:
    path: /data/apps/onlyoffice-documentserver
    state: directory
    owner: docker
    group: docker
    recurse: true
    
- name: pull onlyoffice/documentserver image
  shell: sudo docker pull onlyoffice/documentserver
  register: docker_pull_status

- debug: msg="{{docker_pull_status.stdout}}"

- name: Copy docker-compose.yml to /data/apps/onlyoffice-documentserver
  template:
    src: apps_onlyofficedocumentserver-compose.yml
    dest: /data/apps/onlyoffice-documentserver/docker-compose.yml
    
- name: Run onlyoffice/documentserver
  shell:
    docker-compose up -d
  args:
    chdir: /data/apps/onlyoffice-documentserver

- name: Create symbolic links
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
  with_items:
    - {src: /data/apps/onlyoffice-documentserver/docker-compose.yml,dest: /data/config/docker-compose.yml}
    - {src: /data/apps/onlyoffice-documentserver,dest: /data/wwwroot/onlyoffice-documentserver}
