### 创建phpMyAdmin容器
- name: Started Docker Service
  service:
    name: docker
    state: started
    enabled: yes

- name: pull an phpMyAdmin
  shell: docker pull phpmyadmin/phpmyadmin

- name: Get Docker Gateway
  shell: ip route show | grep docker0 | awk '{print $9}'
  register: gateway
  
- name: Delete the running phpmyadmin
  shell: if [ $(docker ps -aq --filter name=phpmyadmin) ];then docker stop phpmyadmin;docker rm phpmyadmin;fi

- name: Create a phpMyAdmin container
  shell: sudo docker run --name phpmyadmin  \
         --restart=always \
         -i -t -d \
         -p 0.0.0.0:9090:80 \
         -e PMA_HOST={{gateway.stdout}} \
         phpmyadmin
  
  docker_container: 
    name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: yes
    restart_policy: always
    env:
      PMA_HOST={{gateway.stdout}}
    ports: 
      - "0.0.0.0:9090:80"
