- name: Create /data/apps/onlyoffice-documentserver directory
  file:
    path: /data/apps/onlyoffice-documentserver
    state: directory
    owner: docker
    group: docker
    recurse: true

- name: Get Docker Gateway
  shell: ip route show | grep docker0 | awk '{print $9}'
  register: gateway
  
- name: Delete the running phpmyadmin
  shell: if [ $(docker ps -aq --filter name=phpmyadmin) ];then docker stop phpmyadmin;docker rm phpmyadmin;fi

- name: Run phpMyAdmin container
  shell: sudo docker run --name phpmyadmin  \
         --restart=always \
         -i -t -d \
         -p 0.0.0.0:9090:80 \
         -e PMA_HOST={{gateway.stdout}} \
         phpmyadmin/phpmyadmin
