# for different os family
- name: Install for {{ansible_os_family}} os family
  include: "{{ansible_os_family}}.yml"

# install docker and other packages
- name: install Docker
  shell: |
    sudo yum remove docker docker-client docker-client-latest docker-common docker-latest docker-latest-logrotate docker-logrotate docker-engine
    sudo yum install -y yum-utils
    sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    sudo yum install docker-ce docker-ce-cli containerd.io -y

### ln -sf /usr/local/bin/docker-compose  /usr/bin is need, otherwise CentOS on Azure and AWS error
- name: Install Docker Compose
  shell: |
    curl -L "https://github.com/docker/compose/releases/download/{{docker_compose_version}}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
    ln -sf /usr/local/bin/docker-compose  /usr/bin

- name: Started and enable Docker
  service:
    name: docker 
    enabled: yes
    state: restarted

- name: Check Docker Version
  shell: sudo sh -c "docker -v 1>> /data/logs/install_version.txt"

# Docker application installation

- name: Install Docker applications
  include_tasks: apps_{{item}}.yml
  with_items: "{{docker_applications}}"
  when: docker_applications is not none and docker_applications != ""
