
- name: Install required packages
  yum:
    name: [device-mapper-persistent-data,lvm2]

- name: Add Docker repository
  template:
    src: docker.repo.jinja2
    dest: /etc/yum.repos.d/docker.repo

- name: Install Docker on {{ansible_distribution}}
  yum:
    name: [docker-ce,docker-ce-cli,containerd.io]
  when: ansible_distribution != 'Amazon'
  
- name: Install Docker on {{ansible_distribution}}
  yum:
    name: [docker-ce,docker-ce-cli,containerd.io]
    disablerepo: "amzn2-core,amzn2extra-docker"
  when: ansible_distribution == 'Amazon'
