# installation refer to: https://docs.docker.com/engine/install/centos/
# abandon Amazon extra repository for Docker

- name: Install required packages
  yum:
    name: [device-mapper-persistent-data,lvm2]

- name: Add Docker repository
  shell: wget -O /etc/yum.repos.d/docker-ce.repo {{docker_repository_url}}
  
- name: Update release server
  shell: sudo sed -i "s/system-release/centos-release/g" /etc/yum.conf

- name: Install Docker on {{ansible_distribution}}
  yum:
    name: [docker-ce,docker-ce-cli,containerd.io]
    update_cache: yes
    state: latest

- name: Update release server
  shell: sudo sed -i "s/centos-release/system-release/g" /etc/yum.conf
