version: "3.7"
services:
    phppgadmin:
      restart: unless-stopped
      image: dockage/phppgadmin
      ports:
        - "9090:80"
      environment:
        - PHP_PG_ADMIN_SERVER_DESC=PostgreSQL
        - PHP_PG_ADMIN_SERVER_HOST=172.27.0.1
