# CMAK is a tool for managing Apache Kafka clusters
# repository: https://github.com/yahoo/CMAK
# image: https://hub.docker.com/r/hlebalbau/kafka-manager

version: '3.6'
services:
  kafka_manager:
    image: hlebalbau/kafka-manager:latest
    container_name: "{{docker_appname}}"
    ports:
      - "{{docker_apps_cmak_port}}:9000"
    environment:
      ZK_HOSTS: "zoo:2181"
      APPLICATION_SECRET: "random-secret"

networks:
  default:
    external:
      name: "{{docker_addnetwork}}"
