# this comopose file can be running

version: '2.0'

services:

  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /data/wwwroot/portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
