version: "2.2"
services:
  phpmyadmin:
      image: mrvautin/adminmongo
      container_name: "{{docker_appname}}"
      environment:
       - PORT=1234
       - local=en
       - HOST=0.0.0.0
      restart: always
      ports:
       - {{docker_apps_adminmongo_port}}:1234
      volumes:
       - "{{docker_apps_dir}}/{{docker_appname}}/config:/config"
      environment:
        APP_COMMON_DOCKER_VERSION: docker exec -it {{docker_appname}} /bin/sh -c 'cat /app/user/package.json | grep version'

networks:
  default:
    external:
      name: "{{docker_addnetwork}}"
