version: "3.7"
services:
  phpmyadmin:
      image: phpmyadmin
      container_name: phpmyadmin
      environment:
       - PMA_ARBITRARY=1
      restart: always
      ports:
       - 9090:80
      volumes:
       - /sessions

networks:
  default:
    external:
      name: apps
