# refer to: https://helpcenter.onlyoffice.com/server/docker/document/docker-installation.aspx

version: '3'
services:
  onlyoffice-documentserver:
    container_name: onlyoffice-documentserver
    image: onlyoffice/documentserver:latest
    volumes:
      - /data/apps/onlyofficedocumentserver/logs:/var/log/onlyoffice
      - /data/apps/onlyofficedocumentserver/data:/var/www/onlyoffice/Data
      - /data/apps/onlyofficedocumentserver/postgresql:/var/lib/postgresql
    stdin_open: true
    restart: always
    ports:
      - "{{docker_apps_onlyofficedocumentserver_port}}:80"
      
networks:
  default:
    external:
      name: apps
