# refer to: https://helpcenter.onlyoffice.com/server/docker/document/docker-installation.aspx

version: '3'
services:
  onlyoffice-documentserver:
    container_name: onlyoffice-documentserver
    image: onlyoffice/documentserver:latest
    volumes:
      - /data/apps/onlyoffice-documentserver/logs:/var/log/onlyoffice
      - /data/apps/onlyoffice-documentserver/data:/var/www/onlyoffice/Data
      - /data/apps/onlyoffice-documentserver/postgresql:/var/lib/postgresql
    environment:
      - SSL_VERIFY_CLIENT: false
    stdin_open: true
    restart: always
    ports:
      - "{{docker_apps_onlyofficedocumentserver_http_port}}:80"
      - "{{docker_apps_onlyofficedocumentserver_https_port}}:443"
      
networks:
  default:
    external:
      name: apps
