version: "3.7"
services:
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
       - PMA_HOST=172.17.0.1
       - PMA_PORT=3306
      restart: always
      ports:
       - 9090:80
      volumes:
       - /sessions

networks:
  default:
    external:
      name: apps
