# refer to: https://helpcenter.onlyoffice.com/server/docker/document/docker-installation.aspx

version: '3'
services:
  onlyoffice-documentserver:
    container_name: "{{docker_appname}}"
    image: onlyoffice/documentserver:latest
    volumes:
      - "{{docker_apps_dir}}/{{docker_appname}}/logs:/var/log/onlyoffice"
      - "{{docker_apps_dir}}/{{docker_appname}}/data:/var/www/onlyoffice/Data"
      - "{{docker_apps_dir}}/{{docker_appname}}/fonts:/usr/share/fonts/truetype/custom"
      - "{{docker_apps_dir}}/{{docker_appname}}/forgotten:/var/lib/onlyoffice/documentserver/App_Data/cache/files/forgotten"
    stdin_open: true
    restart: always
    ports:
      - "{{docker_apps_onlyofficedocumentserver_port}}:80"
    environment:
      APP_COMMON_DOCKER_VERSION: docker exec -it {{docker_appname}} sh -c 'cat /var/www/onlyoffice/documentserver/web-apps/apps/spreadsheeteditor/main/app.js | sed -n 6p'
      
networks:
  default:
    external:
      name: "{{docker_addnetwork}}"
