# refer to: https://hub.docker.com/_/adminer/

version: "2.0"
services:
  adminer:
      image: adminer
      container_name: "{{docker_appname}}"
      environment:
       - ADMINER_DEFAULT_SERVER={{docker_gateway.stdout}}
      restart: always
      ports:
       - {{docker_apps_adminer_port}}:8080
      environment:
        APP_COMMON_DOCKER_VERSION: docker exec -it {{docker_appname}} sh -c 'cat /var/www/html/adminer.php |grep  @version'
       
networks:
  default:
    external:
      name: "{{docker_addnetwork}}"
